apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: vzhdocker/hipster-frontend:v0.0.1
    name: frontend
    resources: {}
  restartPolicy: Never
